version: 0.2
phases:
    pre_build:
        commands:
            - yum install -y nodejs
            - npm install
    build:
        commands:
            - npm run build
    post_build:
        commands:
            # copy the contents of /build to S3
            # - aws s3 cp --recursive ./build s3://backend-output/
artifacts:
  files:
    - '**/*'
  name: BuildArtifact